# Generated by Django 3.2.5 on 2021-07-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210705_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friends',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
